package com.app.trinsi.search

//list any import classes here.
import com.app.trinsi.model.CATEGORY;
import com.app.trinsi.model.Exercise;
import com.app.trinsi.model.EXERCISE_TYPE;
import java.util.ArrayList;
//declare any global variables here
global String gName;
global EXERCISE_TYPE gExerciseType;
global CATEGORY gExerciseWeight;
global ArrayList exercises;

rule "Search exercises"
    agenda-group "search"
    when
        $e: Exercise( $id: id )
        exerciseName( $id, gName; )
        exerciseType( $id, gExerciseType; )
        exerciseWeight( $id, gExerciseWeight; )
    then
        exercises.add($e);
end

query exerciseName(Long eId, String cName)
    Exercise(id == eId && name.contains(cName))
end

query exerciseType(Long eId, EXERCISE_TYPE cExerciseType)
    Exercise(id == eId && exerciseType == cExerciseType ) or
    Exercise(id == eId && cExerciseType == null)
end

query exerciseWeight(Long eId, CATEGORY cExerciseWeight)
    Exercise(id == eId && exerciseWeight == cExerciseWeight ) or
    Exercise(id == eId && cExerciseWeight == null)
end