package com.app.trinsi.planner

//list any import classes here.
import com.app.trinsi.model.EXERCISE_TYPE;
import com.app.trinsi.model.HEALTH_CONDITION;
import com.app.trinsi.model.PHYSICAL_CHARACTERISTICS;
import com.app.trinsi.model.Exercise;
import com.app.trinsi.model.UserPlanner;
//declare any global variables here

rule "Add exercises"
    when
        $p: UserPlanner(exercises.size() < numOfExercise, $exercises: exercises, $category: category,
                        $exerciseType: exerciseType)
        $e: Exercise(!(this memberOf $exercises), exerciseWeight == $category, exerciseType == $exerciseType)
    then
        modify($p){addExercise($e);}

end

rule "Add exercises, fill"
    salience -100
    when
        $p: UserPlanner(exercises.size() < numOfExercise, $exercises: exercises)
        $e: Exercise() from $exercises
        $n: Integer() from accumulate(
            Exercise(this == $e) from $exercises,
            init (int count = 0;),
            action (count += 1;),
            result (count)
        )
    then
        modify($p){addExercise($e);}
end