INSERT INTO `trinsi`.`user` (`id`, `email`, `name`, `password`, `surname`, `user_role`, `username`, `verified`) VALUES ('1', 'mica97@email.com', 'Milica', '$2a$10$RQQwOzJdOMTNf0hMCE48eexojCSYDbfaBeZ3y1IOkYbd8Z6rHFn2i', 'Travica', 'ROLE_REGULAR', 'mica', b'1');
INSERT INTO `trinsi`.`user` (`id`, `email`, `name`, `password`, `surname`, `user_role`, `username`, `verified`) VALUES ('2', 'cupka2797@gmail.com', 'Milica', '$2a$10$RQQwOzJdOMTNf0hMCE48eexojCSYDbfaBeZ3y1IOkYbd8Z6rHFn2i', 'Travica', 'ROLE_ADMIN', 'milovica', b'1');
INSERT INTO `trinsi`.`user` (`id`, `email`, `name`, `password`, `surname`, `user_role`, `username`, `verified`) VALUES ('3', 'cupka2797+1@gmail.com', 'Milica', '$2a$10$RQQwOzJdOMTNf0hMCE48eexojCSYDbfaBeZ3y1IOkYbd8Z6rHFn2i', 'Travica', 'ROLE_REGULAR', 'korisnik1', b'1');
INSERT INTO `trinsi`.`user` (`id`, `email`, `name`, `password`, `surname`, `user_role`, `username`, `verified`) VALUES ('4', 'cupka2797+2@gmail.com', 'Milica', '$2a$10$RQQwOzJdOMTNf0hMCE48eexojCSYDbfaBeZ3y1IOkYbd8Z6rHFn2i', 'Travica', 'ROLE_REGULAR', 'korisnik2', b'1');

INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (1,'Opis vežbe','STRETCHES','BEGINNER','Vežba istezanja 1');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (2,'Opis vežbe','STRETCHES','MIDDLE','Vežba istezanja 2');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (3,'Opis vežbe','STRETCHES','ADVANCED','Vežba istezanja 3');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (4,'Opis vežbe','STRENGTHS','BEGINNER','Vežba snage 1');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (5,'Opis vežbe','STRENGTHS','MIDDLE','Vežba snage 2');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (6,'Opis vežbe','STRENGTHS','ADVANCED','Vežba snage 3');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (7,'Opis vežbe','CARDIO','BEGINNER','Kardio vežba 1');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (8,'Opis vežbe','CARDIO','MIDDLE','Kardio vežba 2');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (9,'Opis vežbe','CARDIO','ADVANCED','Kardio vežba 3');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (10,'Opis vežbe','WEIGHT_LOSS','BEGINNER','Vežba mršavljenja 1');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (11,'Opis vežbe','WEIGHT_LOSS','MIDDLE','Vežba mršavljenja 2');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (12,'Opis vežbe','WEIGHT_LOSS','ADVANCED','Vežba mršavljenja 3');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (13,'Opis vežbe','STRETCHES','BEGINNER','Vežba istezanja 4');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (14,'Opis vežbe','STRETCHES','MIDDLE','Vežba istezanja 5');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (15,'Opis vežbe','STRETCHES','ADVANCED','Vežba istezanja 6');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (16,'Opis vežbe','STRENGTHS','BEGINNER','Vežba snage 4');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (17,'Opis vežbe','STRENGTHS','MIDDLE','Vežba snage 5');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (18,'Opis vežbe','STRENGTHS','ADVANCED','Vežba snage 6');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (19,'Opis vežbe','CARDIO','BEGINNER','Kardio vežba 4');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (20,'Opis vežbe','CARDIO','MIDDLE','Kardio vežba 5');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (21,'Opis vežbe','CARDIO','ADVANCED','Kardio vežba 6');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (22,'Opis vežbe','WEIGHT_LOSS','BEGINNER','Vežba mršavljenja 4');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (23,'Opis vežbe','WEIGHT_LOSS','MIDDLE','Vežba mršavljenja 5');
INSERT INTO `trinsi`.`exercise` (`id`,`description`,`exercise_type`,`exercise_weight`,`name`) VALUES (24,'Opis vežbe','WEIGHT_LOSS','ADVANCED','Vežba mršavljenja 6');
